In [1]:
#hago un ejercicio completo del archivo loan-csv

In [2]:
import numpy as np

In [3]:
#mejoro la forma en la que veo los archivos
np.set_printoptions(suppress= True, linewidth=100, precision=2)
#evita notacion cientifica, 100 caracteres en una linea, 2 digitos decimales

In [4]:
#Importo los datos

In [5]:
#pruebo con loadtxt() a ver si tira error es que tiene datos faltantes. Tiro error por lo que uso genfromtxt()
row_data_np = np.genfromtxt('E:\FRANCO\Curso Data Analyst\S28 - A Loan Data Example with NumPy\loan-data.csv',
                         delimiter=';')
row_data_np

array([[        nan,         nan,         nan, ...,         nan,         nan,         nan],
       [48010226.  ,         nan,    35000.  , ...,         nan,         nan,     9452.96],
       [57693261.  ,         nan,    30000.  , ...,         nan,         nan,     4679.7 ],
       ...,
       [50415990.  ,         nan,    10000.  , ...,         nan,         nan,     2185.64],
       [46154151.  ,         nan,         nan, ...,         nan,         nan,     3199.4 ],
       [66055249.  ,         nan,    10000.  , ...,         nan,         nan,      301.9 ]])

In [6]:
#Chequeando la data imcompleta

In [7]:
np.isnan(row_data_np).sum()

88019

In [8]:
temporary_fill = np.nanmax(row_data_np) +1 #valor mas grande que el maximo
temporary_mean = np.nanmean(row_data_np, axis=0)  #promedio de cada columna

C:\Users\franc\AppData\Local\Temp\ipykernel_3828\1099272035.py:2: RuntimeWarning: Mean of empty slice
  temporary_mean = np.nanmean(row_data_np, axis=0)  #promedio de cada columna


In [9]:
temporary_mean #veo que hay varias columnas con valores faltantes o que son de tipo string

array([54015809.19,         nan,    15273.46,         nan,    15311.04,         nan,       16.62,
            440.92,         nan,         nan,         nan,         nan,         nan,     3143.85])

In [10]:
#guardo estos valores auxiliares para luego usarlos. Tira advertencia por que toma como columnas vacias a las que son solo strings
temporary_stats = np.array([np.nanmin(row_data_np, axis=0),
                            temporary_mean,
                            np.nanmax(row_data_np, axis=0)])

C:\Users\franc\AppData\Local\Temp\ipykernel_3828\874137032.py:2: RuntimeWarning: All-NaN slice encountered
  temporary_stats = np.array([np.nanmin(row_data_np, axis=0),
C:\Users\franc\AppData\Local\Temp\ipykernel_3828\874137032.py:4: RuntimeWarning: All-NaN slice encountered
  np.nanmax(row_data_np, axis=0)])


In [11]:
temporary_stats

array([[  373332.  ,         nan,     1000.  ,         nan,     1000.  ,         nan,        6.  ,
              31.42,         nan,         nan,         nan,         nan,         nan,        0.  ],
       [54015809.19,         nan,    15273.46,         nan,    15311.04,         nan,       16.62,
             440.92,         nan,         nan,         nan,         nan,         nan,     3143.85],
       [68616519.  ,         nan,    35000.  ,         nan,    35000.  ,         nan,       28.99,
            1372.97,         nan,         nan,         nan,         nan,         nan,    41913.62]])

        Splitting dataset

In [12]:
#Splitting (dividiendo) las columnas. Separo las que sean string y las que sean numeros

In [13]:
#argwhere por defecto comprueba si los valores son !=0 .Si la columna contiene solo texto, su media es nan, entonces isnan da True.
#luego devuelve el indice de esa columna en el dataset original
columns_strings = np.argwhere(np.isnan(temporary_mean)).squeeze() #uso squeeze() por que da un arreglo 2D y quiero 1D
columns_strings

array([ 1,  3,  5,  8,  9, 10, 11, 12], dtype=int64)

In [14]:
#ahora para ver las columnas que contienen valores numericos
columns_numeric = np.argwhere(np.isnan(temporary_mean) == False).squeeze() #uso squeeze() por que da un arreglo 2D y quiero 1D
columns_numeric

array([ 0,  2,  4,  6,  7, 13], dtype=int64)

    Reimporto el dataset como 2 distintos

In [15]:
#creo un dataset para solo las columnas con datos strings
loan_data_strings = np.genfromtxt('E:\FRANCO\Curso Data Analyst\S28 - A Loan Data Example with NumPy\loan-data.csv',
                         delimiter=';',
                         skip_header=1 ,
                         autostrip = True,
                         usecols= columns_strings,
                         dtype = str)
loan_data_strings

array([['May-15', 'Current', '36 months', ..., 'Verified',
        'https://www.lendingclub.com/browse/loanDetail.action?loan_id=48010226', 'CA'],
       ['', 'Current', '36 months', ..., 'Source Verified',
        'https://www.lendingclub.com/browse/loanDetail.action?loan_id=57693261', 'NY'],
       ['Sep-15', 'Current', '36 months', ..., 'Verified',
        'https://www.lendingclub.com/browse/loanDetail.action?loan_id=59432726', 'PA'],
       ...,
       ['Jun-15', 'Current', '36 months', ..., 'Source Verified',
        'https://www.lendingclub.com/browse/loanDetail.action?loan_id=50415990', 'CA'],
       ['Apr-15', 'Current', '36 months', ..., 'Source Verified',
        'https://www.lendingclub.com/browse/loanDetail.action?loan_id=46154151', 'OH'],
       ['Dec-15', 'Current', '36 months', ..., '',
        'https://www.lendingclub.com/browse/loanDetail.action?loan_id=66055249', 'IL']],
      dtype='<U69')

In [16]:
#creo un dataset para solo las columnas con datos numericos
loan_data_numeric = np.genfromtxt('E:\FRANCO\Curso Data Analyst\S28 - A Loan Data Example with NumPy\loan-data.csv',
                         delimiter=';',
                         skip_header=1 ,
                         autostrip = True,
                         usecols= columns_numeric,
                         filling_values = temporary_fill)
loan_data_numeric

array([[48010226.  ,    35000.  ,    35000.  ,       13.33,     1184.86,     9452.96],
       [57693261.  ,    30000.  ,    30000.  , 68616520.  ,      938.57,     4679.7 ],
       [59432726.  ,    15000.  ,    15000.  , 68616520.  ,      494.86,     1969.83],
       ...,
       [50415990.  ,    10000.  ,    10000.  , 68616520.  , 68616520.  ,     2185.64],
       [46154151.  , 68616520.  ,    10000.  ,       16.55,      354.3 ,     3199.4 ],
       [66055249.  ,    10000.  ,    10000.  , 68616520.  ,      309.97,      301.9 ]])

In [17]:
#nombre de las columnas

In [18]:
header_full = np.genfromtxt('E:\FRANCO\Curso Data Analyst\S28 - A Loan Data Example with NumPy\loan-data.csv',
                            delimiter=';',
                            max_rows=1,
                            dtype = str)

header_full

array(['id', 'issue_d', 'loan_amnt', 'loan_status', 'funded_amnt', 'term', 'int_rate',
       'installment', 'grade', 'sub_grade', 'verification_status', 'url', 'addr_state',
       'total_pymnt'], dtype='<U19')

In [19]:
#creo 2 variables, una contiene los nombres de las columnas con string y la otra de las columnas numericas
header_string, header_numeric = header_full[columns_strings],header_full[columns_numeric]

In [20]:
header_string

array(['issue_d', 'loan_status', 'term', 'grade', 'sub_grade', 'verification_status', 'url',
       'addr_state'], dtype='<U19')

In [21]:
header_numeric

array(['id', 'loan_amnt', 'funded_amnt', 'int_rate', 'installment', 'total_pymnt'], dtype='<U19')

        Crear Checkpoints

In [22]:
def checkpoint(filename, checkpoint_header, checkpoint_data):
    np.savez(filename, header=checkpoint_header, data=checkpoint_data)
    checkpoint_variable = np.load(filename + ".npz")
    return(checkpoint_variable)

In [23]:
checkpoint_test = checkpoint("checkpoint-test", header_string, loan_data_strings)

In [24]:
checkpoint_test['data']

array([['May-15', 'Current', '36 months', ..., 'Verified',
        'https://www.lendingclub.com/browse/loanDetail.action?loan_id=48010226', 'CA'],
       ['', 'Current', '36 months', ..., 'Source Verified',
        'https://www.lendingclub.com/browse/loanDetail.action?loan_id=57693261', 'NY'],
       ['Sep-15', 'Current', '36 months', ..., 'Verified',
        'https://www.lendingclub.com/browse/loanDetail.action?loan_id=59432726', 'PA'],
       ...,
       ['Jun-15', 'Current', '36 months', ..., 'Source Verified',
        'https://www.lendingclub.com/browse/loanDetail.action?loan_id=50415990', 'CA'],
       ['Apr-15', 'Current', '36 months', ..., 'Source Verified',
        'https://www.lendingclub.com/browse/loanDetail.action?loan_id=46154151', 'OH'],
       ['Dec-15', 'Current', '36 months', ..., '',
        'https://www.lendingclub.com/browse/loanDetail.action?loan_id=66055249', 'IL']],
      dtype='<U69')

In [25]:
#chequeo que la data es igual a la que tengo
np.array_equal(checkpoint_test['data'],loan_data_strings)

True

        Manipulando las columnas strings

In [26]:
header_string

array(['issue_d', 'loan_status', 'term', 'grade', 'sub_grade', 'verification_status', 'url',
       'addr_state'], dtype='<U19')

In [27]:
#cambio el nombre de la primer columna para que sea mas entendible
header_string[0] = "issue_date"

In [28]:
loan_data_strings

array([['May-15', 'Current', '36 months', ..., 'Verified',
        'https://www.lendingclub.com/browse/loanDetail.action?loan_id=48010226', 'CA'],
       ['', 'Current', '36 months', ..., 'Source Verified',
        'https://www.lendingclub.com/browse/loanDetail.action?loan_id=57693261', 'NY'],
       ['Sep-15', 'Current', '36 months', ..., 'Verified',
        'https://www.lendingclub.com/browse/loanDetail.action?loan_id=59432726', 'PA'],
       ...,
       ['Jun-15', 'Current', '36 months', ..., 'Source Verified',
        'https://www.lendingclub.com/browse/loanDetail.action?loan_id=50415990', 'CA'],
       ['Apr-15', 'Current', '36 months', ..., 'Source Verified',
        'https://www.lendingclub.com/browse/loanDetail.action?loan_id=46154151', 'OH'],
       ['Dec-15', 'Current', '36 months', ..., '',
        'https://www.lendingclub.com/browse/loanDetail.action?loan_id=66055249', 'IL']],
      dtype='<U69')

    issue date

In [29]:
#primer columna del dataset. muestro los valores unicos
np.unique(loan_data_strings[:,0])

array(['', 'Apr-15', 'Aug-15', 'Dec-15', 'Feb-15', 'Jan-15', 'Jul-15', 'Jun-15', 'Mar-15',
       'May-15', 'Nov-15', 'Oct-15', 'Sep-15'], dtype='<U69')

In [30]:
#como son todos del año 15 puedo eliminar esa parte del texto
loan_data_strings[:,0] = np.chararray.strip(loan_data_strings[:,0], "-15")

In [31]:
np.unique(loan_data_strings[:,0])

array(['', 'Apr', 'Aug', 'Dec', 'Feb', 'Jan', 'Jul', 'Jun', 'Mar', 'May', 'Nov', 'Oct', 'Sep'],
      dtype='<U69')

In [32]:
#quiero substituir los meses por numeros para que sea mejor y ocupe menos espacio

In [33]:
months = np.array(['', 'Jan', 'Feb', 'Mar', 'Apr', 'May', 'Jun', 'Jul', 'Aug', 'Sep', 'Oct', 'Nov', 'Dec'])

In [34]:
for i in range (13):
    loan_data_strings[:,0] = np.where(loan_data_strings[:,0] == months[i],
                                      i,
                                      loan_data_strings[:,0])

In [35]:
np.unique(loan_data_strings[:,0])

array(['0', '1', '10', '11', '12', '2', '3', '4', '5', '6', '7', '8', '9'], dtype='<U69')

    loan_status

In [36]:
header_string

array(['issue_date', 'loan_status', 'term', 'grade', 'sub_grade', 'verification_status', 'url',
       'addr_state'], dtype='<U19')

In [37]:
#veo si todos los valores son iguales o no
np.unique(loan_data_strings[:,1])

array(['', 'Charged Off', 'Current', 'Default', 'Fully Paid', 'In Grace Period', 'Issued',
       'Late (16-30 days)', 'Late (31-120 days)'], dtype='<U69')

In [38]:
#voy a separar los 9 resultados en buenos y malos (1:good ,0:bad) ya que me piden ver las cuentas buenas o malas segun como pagan o si estan atrasados

In [39]:
status_bad = np.array(['', 'Charged Off', 'Default', 'Late (31-120 days)'])

In [40]:
loan_data_strings[:,1] = np.where(np.isin(loan_data_strings[:,1],status_bad), 0,1) #me fijo si estan y asingo 0 o 1

In [41]:
#verifico
np.unique(loan_data_strings[:,1])

array(['0', '1'], dtype='<U69')

    term

In [42]:
header_string

array(['issue_date', 'loan_status', 'term', 'grade', 'sub_grade', 'verification_status', 'url',
       'addr_state'], dtype='<U19')

In [43]:
loan_data_strings[:,2]

array(['36 months', '36 months', '36 months', ..., '36 months', '36 months', '36 months'],
      dtype='<U69')

In [44]:
np.unique(loan_data_strings[:,2])

array(['', '36 months', '60 months'], dtype='<U69')

In [45]:
#elimino el texto months
loan_data_strings[:,2] = np.chararray.strip(loan_data_strings[:,2], " months")
loan_data_strings[:,2]

array(['36', '36', '36', ..., '36', '36', '36'], dtype='<U69')

In [46]:
#cambio el nombre de la columna
header_string[2] = "term_months"

In [47]:
#cambio el valor a '60' para los espacios vacios por que se supone el peor de los casos en la consigna
loan_data_strings[:,2] = np.where(loan_data_strings[:,2] == '',
                                  '60',
                                  loan_data_strings[:,2])
loan_data_strings[:,2]

array(['36', '36', '36', ..., '36', '36', '36'], dtype='<U69')

In [48]:
np.unique(loan_data_strings[:,2])

array(['36', '60'], dtype='<U69')

    grade and sub_grade

In [49]:
header_string

array(['issue_date', 'loan_status', 'term_months', 'grade', 'sub_grade', 'verification_status',
       'url', 'addr_state'], dtype='<U19')

In [50]:
np.unique(loan_data_strings[:,3])

array(['', 'A', 'B', 'C', 'D', 'E', 'F', 'G'], dtype='<U69')

In [51]:
np.unique(loan_data_strings[:,4])

array(['', 'A1', 'A2', 'A3', 'A4', 'A5', 'B1', 'B2', 'B3', 'B4', 'B5', 'C1', 'C2', 'C3', 'C4',
       'C5', 'D1', 'D2', 'D3', 'D4', 'D5', 'E1', 'E2', 'E3', 'E4', 'E5', 'F1', 'F2', 'F3', 'F4',
       'F5', 'G1', 'G2', 'G3', 'G4', 'G5'], dtype='<U69')

     filling sub_grade

In [52]:
for i in np.unique(loan_data_strings[:,3])[1:]: #recorro despues de la primera por que esta vacia
    #compruebo si no hay subgrade y si falta se fija si el grado es igual al de la iteracion actual
    loan_data_strings[:,4] = np.where((loan_data_strings[:,4] == '') & (loan_data_strings[:,3]== i),
                                      i + '5',
                                      loan_data_strings[:,4])

In [53]:
np.unique(loan_data_strings[:,4], return_counts = True)
#veo que hay 9 valores que no contienen grade ni sub_grade

(array(['', 'A1', 'A2', 'A3', 'A4', 'A5', 'B1', 'B2', 'B3', 'B4', 'B5', 'C1', 'C2', 'C3', 'C4',
        'C5', 'D1', 'D2', 'D3', 'D4', 'D5', 'E1', 'E2', 'E3', 'E4', 'E5', 'F1', 'F2', 'F3', 'F4',
        'F5', 'G1', 'G2', 'G3', 'G4', 'G5'], dtype='<U69'),
 array([  9, 285, 278, 239, 323, 592, 509, 517, 530, 553, 633, 629, 567, 586, 564, 577, 391, 267,
        250, 255, 288, 235, 162, 171, 139, 160,  94,  52,  34,  43,  24,  19,  10,   3,   7,   5],
       dtype=int64))

In [54]:
#creo un nuevo sub grado que se llame H1
loan_data_strings[:,4] = np.where((loan_data_strings[:,4] == ''),
                                      'H1',
                                      loan_data_strings[:,4])

In [55]:
np.unique(loan_data_strings[:,4])

array(['A1', 'A2', 'A3', 'A4', 'A5', 'B1', 'B2', 'B3', 'B4', 'B5', 'C1', 'C2', 'C3', 'C4', 'C5',
       'D1', 'D2', 'D3', 'D4', 'D5', 'E1', 'E2', 'E3', 'E4', 'E5', 'F1', 'F2', 'F3', 'F4', 'F5',
       'G1', 'G2', 'G3', 'G4', 'G5', 'H1'], dtype='<U69')

In [56]:
#Removing grade

In [57]:
#Ahora no hace falta el grado, con solo tener subgrade alcanza, por lo que lo remuevo
loan_data_strings = np.delete(loan_data_strings, 3, axis=1)

In [58]:
loan_data_strings[:,3] #veo que ahora la columna 3 es la de sub_grade

array(['C3', 'A5', 'B5', ..., 'A5', 'D2', 'A4'], dtype='<U69')

In [59]:
#tengo que borrar de la cabecera tambien
header_string = np.delete(header_string, 3) #elimina la 3 columna

In [60]:
#verifico
header_string[3]

'sub_grade'

    Converting subgrade

In [61]:
np.unique(loan_data_strings[:,3])

array(['A1', 'A2', 'A3', 'A4', 'A5', 'B1', 'B2', 'B3', 'B4', 'B5', 'C1', 'C2', 'C3', 'C4', 'C5',
       'D1', 'D2', 'D3', 'D4', 'D5', 'E1', 'E2', 'E3', 'E4', 'E5', 'F1', 'F2', 'F3', 'F4', 'F5',
       'G1', 'G2', 'G3', 'G4', 'G5', 'H1'], dtype='<U69')

In [62]:
#quiero convertir estos valores en numeros, en vez de usar where muchas veces utilizo un diccionario

In [63]:
keys = list(np.unique(loan_data_strings[:,3]))
values = list(range(1, np.unique(loan_data_strings[:,3]).shape[0]+1))
dict_sub_grade = dict(zip(keys,values))

In [64]:
dict_sub_grade

{'A1': 1,
 'A2': 2,
 'A3': 3,
 'A4': 4,
 'A5': 5,
 'B1': 6,
 'B2': 7,
 'B3': 8,
 'B4': 9,
 'B5': 10,
 'C1': 11,
 'C2': 12,
 'C3': 13,
 'C4': 14,
 'C5': 15,
 'D1': 16,
 'D2': 17,
 'D3': 18,
 'D4': 19,
 'D5': 20,
 'E1': 21,
 'E2': 22,
 'E3': 23,
 'E4': 24,
 'E5': 25,
 'F1': 26,
 'F2': 27,
 'F3': 28,
 'F4': 29,
 'F5': 30,
 'G1': 31,
 'G2': 32,
 'G3': 33,
 'G4': 34,
 'G5': 35,
 'H1': 36}

In [65]:
#recorre todos los subgrade y los reemplaza por el valor del diccionario
for i in np.unique(loan_data_strings[:,3]):
    loan_data_strings[:,3] = np.where(loan_data_strings[:,3] == i,
                             dict_sub_grade[i],
                             loan_data_strings[:,3])

In [66]:
np.unique(loan_data_strings[:,3]) #verifico

array(['1', '10', '11', '12', '13', '14', '15', '16', '17', '18', '19', '2', '20', '21', '22',
       '23', '24', '25', '26', '27', '28', '29', '3', '30', '31', '32', '33', '34', '35', '36',
       '4', '5', '6', '7', '8', '9'], dtype='<U69')

    Verification status

In [67]:
header_string

array(['issue_date', 'loan_status', 'term_months', 'sub_grade', 'verification_status', 'url',
       'addr_state'], dtype='<U19')

In [68]:
np.unique(loan_data_strings[:,4])

array(['', 'Not Verified', 'Source Verified', 'Verified'], dtype='<U69')

In [69]:
#sustituyo las malas opciones ('' y 'Not verified') por 0 y las otras por 1
loan_data_strings[:,4] = np.where((loan_data_strings[:,4] == '') | (loan_data_strings[:,4] == 'Not Verified'),
                                  0, #si se cumple
                                  1) #si no se cumple

In [70]:
#verifico
np.unique(loan_data_strings[:,4])

array(['0', '1'], dtype='<U69')

    URL

In [71]:
loan_data_strings[:,5]

array(['https://www.lendingclub.com/browse/loanDetail.action?loan_id=48010226',
       'https://www.lendingclub.com/browse/loanDetail.action?loan_id=57693261',
       'https://www.lendingclub.com/browse/loanDetail.action?loan_id=59432726', ...,
       'https://www.lendingclub.com/browse/loanDetail.action?loan_id=50415990',
       'https://www.lendingclub.com/browse/loanDetail.action?loan_id=46154151',
       'https://www.lendingclub.com/browse/loanDetail.action?loan_id=66055249'], dtype='<U69')

In [72]:
#son todas iguales hasta la parte de loan_id por lo que la elimino
np.chararray.strip(loan_data_strings[:,5], 'https://www.lendingclub.com/browse/loanDetail.action?loan_id=')

chararray(['48010226', '57693261', '59432726', ..., '50415990', '46154151', '66055249'],
          dtype='<U69')

In [73]:
#sobreescribo la columna ya que no se pierde data importante 
loan_data_strings[:,5] = np.chararray.strip(loan_data_strings[:,5], 'https://www.lendingclub.com/browse/loanDetail.action?loan_id=')

In [74]:
loan_data_strings[:,5]

array(['48010226', '57693261', '59432726', ..., '50415990', '46154151', '66055249'], dtype='<U69')

In [75]:
#me fijo en la cabecera completa por que ya habia una columna con nombre id_ 
header_full

array(['id', 'issue_d', 'loan_amnt', 'loan_status', 'funded_amnt', 'term', 'int_rate',
       'installment', 'grade', 'sub_grade', 'verification_status', 'url', 'addr_state',
       'total_pymnt'], dtype='<U19')

In [76]:
#veo si son iguales los id con el loan_id del url

In [77]:
loan_data_numeric[:,0].astype(dtype = np.int32)

array([48010226, 57693261, 59432726, ..., 50415990, 46154151, 66055249])

In [78]:
loan_data_strings[:,5].astype(dtype = np.int32)

array([48010226, 57693261, 59432726, ..., 50415990, 46154151, 66055249])

In [79]:
#verifico que sean iguales
np.array_equal(loan_data_numeric[:,0].astype(dtype = np.int32),loan_data_strings[:,5].astype(dtype = np.int32) )

True

In [80]:
#Como son iguales, la columna URL no contiene informacion adicional por lo que la elimino

In [81]:
loan_data_strings = np.delete(loan_data_strings, 5, axis=1)
header_string = np.delete(header_string, 5)

In [82]:
#verifico que se haya eliminado
loan_data_strings[:,5]

array(['CA', 'NY', 'PA', ..., 'CA', 'OH', 'IL'], dtype='<U69')

In [83]:
#verifico tambien
header_string

array(['issue_date', 'loan_status', 'term_months', 'sub_grade', 'verification_status',
       'addr_state'], dtype='<U19')

In [84]:
#verifico por las dudas que sigan los valores de ID
loan_data_numeric[:,0]

array([48010226., 57693261., 59432726., ..., 50415990., 46154151., 66055249.])

In [85]:
header_numeric

array(['id', 'loan_amnt', 'funded_amnt', 'int_rate', 'installment', 'total_pymnt'], dtype='<U19')

    State address

In [86]:
header_string

array(['issue_date', 'loan_status', 'term_months', 'sub_grade', 'verification_status',
       'addr_state'], dtype='<U19')

In [87]:
header_string[5] = "state_address"

In [88]:
#vemos que falta un estado. Iowa
#ordeno los estados y las cantidades en variables nuevas. Luego ordeno descendientemente las cantidades
state_names, state_count = np.unique(loan_data_strings[:,5],return_counts = True)
state_count_sorted = np.argsort(-state_count)
state_names[state_count_sorted], state_count[state_count_sorted]

(array(['CA', 'NY', 'TX', 'FL', '', 'IL', 'NJ', 'GA', 'PA', 'OH', 'MI', 'NC', 'VA', 'MD', 'AZ',
        'WA', 'MA', 'CO', 'MO', 'MN', 'IN', 'WI', 'CT', 'TN', 'NV', 'AL', 'LA', 'OR', 'SC', 'KY',
        'KS', 'OK', 'UT', 'AR', 'MS', 'NH', 'NM', 'WV', 'HI', 'RI', 'MT', 'DE', 'DC', 'WY', 'AK',
        'NE', 'SD', 'VT', 'ND', 'ME'], dtype='<U69'),
 array([1336,  777,  758,  690,  500,  389,  341,  321,  320,  312,  267,  261,  242,  222,  220,
         216,  210,  201,  160,  156,  152,  148,  143,  143,  130,  119,  116,  108,  107,   84,
          84,   83,   74,   74,   61,   58,   57,   49,   44,   40,   28,   27,   27,   27,   26,
          25,   24,   17,   16,   10], dtype=int64))

In [89]:
#asigno a 0 los datos de estado faltante
loan_data_strings[:,5] = np.where(loan_data_strings[:,5] == '',
                                  0,
                                  loan_data_strings[:,5])

In [99]:
#separo los estados en regiones: este, oeste, midwest, sur
states_west = np.array(['WA','OR','CA','NV','ID','MT','WY','UT','CO','AZ','NM','HI','AK'])
states_south = np.array(['TX','OK','AR','LA','MS','AL','TN','KY','FL','GA','SC','NC','VA','WV','MD','DE','DC'])
states_midwest = np.array(['ND','SD','NE','KS','MN','IA','MO','WI','IL','IN','MI','OH'])
states_east = np.array(['PA','NY','NJ','CT','MA','VT','NH','ME','RI'])

In [100]:
#asigno si son del west:1, south:2, midwest:3, east:4
loan_data_strings[:,5] = np.where(np.isin(loan_data_strings[:,5], states_west), 1, loan_data_strings[:,5])
loan_data_strings[:,5] = np.where(np.isin(loan_data_strings[:,5], states_south), 2, loan_data_strings[:,5])
loan_data_strings[:,5] = np.where(np.isin(loan_data_strings[:,5], states_midwest), 3, loan_data_strings[:,5])
loan_data_strings[:,5] = np.where(np.isin(loan_data_strings[:,5], states_east), 4, loan_data_strings[:,5])

In [101]:
#verifico que se cambio bien
np.unique(loan_data_strings[:,5])

array(['0', '1', '2', '3', '4'], dtype='<U69')

    Converting to numbers

In [102]:
loan_data_strings

array([['5', '1', '36', '13', '1', '1'],
       ['0', '1', '36', '5', '1', '4'],
       ['9', '1', '36', '10', '1', '4'],
       ...,
       ['6', '1', '36', '5', '1', '1'],
       ['4', '1', '36', '17', '1', '3'],
       ['12', '1', '36', '4', '0', '3']], dtype='<U69')

In [104]:
loan_data_strings = loan_data_strings.astype(int)

In [105]:
loan_data_strings

array([[ 5,  1, 36, 13,  1,  1],
       [ 0,  1, 36,  5,  1,  4],
       [ 9,  1, 36, 10,  1,  4],
       ...,
       [ 6,  1, 36,  5,  1,  1],
       [ 4,  1, 36, 17,  1,  3],
       [12,  1, 36,  4,  0,  3]])

    Checkpoint 1 : Strings

In [107]:
checkpoint_strings = checkpoint("Checkpoint-Strings", header_string, loan_data_strings)

In [110]:
#verifico
checkpoint_strings["header"]

array(['issue_date', 'loan_status', 'term_months', 'sub_grade', 'verification_status',
       'state_address'], dtype='<U19')

In [111]:
#verifico
checkpoint_strings["data"]

array([[ 5,  1, 36, 13,  1,  1],
       [ 0,  1, 36,  5,  1,  4],
       [ 9,  1, 36, 10,  1,  4],
       ...,
       [ 6,  1, 36,  5,  1,  1],
       [ 4,  1, 36, 17,  1,  3],
       [12,  1, 36,  4,  0,  3]])

In [112]:
np.array_equal(checkpoint_strings["data"], loan_data_strings)

True

    Manipulating numeric columns

In [113]:
loan_data_numeric

array([[48010226.  ,    35000.  ,    35000.  ,       13.33,     1184.86,     9452.96],
       [57693261.  ,    30000.  ,    30000.  , 68616520.  ,      938.57,     4679.7 ],
       [59432726.  ,    15000.  ,    15000.  , 68616520.  ,      494.86,     1969.83],
       ...,
       [50415990.  ,    10000.  ,    10000.  , 68616520.  , 68616520.  ,     2185.64],
       [46154151.  , 68616520.  ,    10000.  ,       16.55,      354.3 ,     3199.4 ],
       [66055249.  ,    10000.  ,    10000.  , 68616520.  ,      309.97,      301.9 ]])

In [114]:
#me fijo si faltan valores
np.isnan(loan_data_numeric).sum()

0

    Substitute filler values

In [117]:
#segun el enunciado debo sustituir los peores valores, ya que en este caso no hay valores faltantes sino que se cambiaron por el filler_value

In [116]:
header_numeric

array(['id', 'loan_amnt', 'funded_amnt', 'int_rate', 'installment', 'total_pymnt'], dtype='<U19')

In [118]:
 #id

In [120]:
temporary_fill #me fijo si hay valores faltantes que se cambiaron por este valor

68616520.0

In [121]:
np.isin(loan_data_numeric[:,0], temporary_fill)

array([False, False, False, ..., False, False, False])

In [123]:
np.isin(loan_data_numeric[:,0], temporary_fill).sum() #como da 0 no hubo que rellenar valores en esta columna

0

In [129]:
#veo los valores que guarde de temporary_stats 
temporary_stats[:, columns_numeric] #fila de arriba:minimos, fila del medio: medias, fila abajo: maximos

array([[  373332.  ,     1000.  ,     1000.  ,        6.  ,       31.42,        0.  ],
       [54015809.19,    15273.46,    15311.04,       16.62,      440.92,     3143.85],
       [68616519.  ,    35000.  ,    35000.  ,       28.99,     1372.97,    41913.62]])

In [130]:
#quiero que la columnas 'funded_amnt' sean los valores faltantes iguales al minimo de temporary_stats
loan_data_numeric[:,2]

array([35000., 30000., 15000., ..., 10000., 10000., 10000.])

In [132]:
#reemplazo los valores por el minimo de funded_amnt
loan_data_numeric[:,2] = np.where(loan_data_numeric[:,2]==temporary_fill,
                                  temporary_stats[0, columns_numeric[2]],
                                  loan_data_numeric[:,2])
loan_data_numeric[:,2]

array([35000., 30000., 15000., ..., 10000., 10000., 10000.])

    Loaned_amount, Interest_rate, Total_payment, Installment

In [133]:
#En estas columnas voy a reemplazar por el valor maximo

In [134]:
header_numeric

array(['id', 'loan_amnt', 'funded_amnt', 'int_rate', 'installment', 'total_pymnt'], dtype='<U19')

In [136]:
#lo mismo que arriba pero para las 4 columnas y cambiando el valor por el maximo
for i in [1,3,4,5]:
    loan_data_numeric[:,i] = np.where(loan_data_numeric[:,i]==temporary_fill,
                                  temporary_stats[2, columns_numeric[i]],
                                  loan_data_numeric[:,i])

In [137]:
loan_data_numeric

array([[48010226.  ,    35000.  ,    35000.  ,       13.33,     1184.86,     9452.96],
       [57693261.  ,    30000.  ,    30000.  ,       28.99,      938.57,     4679.7 ],
       [59432726.  ,    15000.  ,    15000.  ,       28.99,      494.86,     1969.83],
       ...,
       [50415990.  ,    10000.  ,    10000.  ,       28.99,     1372.97,     2185.64],
       [46154151.  ,    35000.  ,    10000.  ,       16.55,      354.3 ,     3199.4 ],
       [66055249.  ,    10000.  ,    10000.  ,       28.99,      309.97,      301.9 ]])

    Currency change

The exchange rate: tipo de cambio

In [138]:
#necesito los valores en dolares y en euros

In [140]:
EUR_USD = np.genfromtxt('E:\FRANCO\Curso Data Analyst\S28 - A Loan Data Example with NumPy\EUR-USD.csv',
                        delimiter=',',
                        autostrip=True,
                       dtype=str)
EUR_USD

array([['Open', 'High', 'Low', 'Close', 'Volume'],
       ['1.2098628282546997', '1.2098628282546997', '1.11055588722229', '1.1287955045700073', '0'],
       ['1.1287955045700073', '1.1484194993972778', '1.117680549621582', '1.1205360889434814',
        '0'],
       ['1.119795799255371', '1.1240400075912476', '1.0460032224655151', '1.0830246210098267',
        '0'],
       ['1.0741022825241089', '1.1247594356536865', '1.0521597862243652', '1.1114321947097778',
        '0'],
       ['1.1215037107467651', '1.145304799079895', '1.0821995735168457', '1.0960345268249512',
        '0'],
       ['1.095902442932129', '1.1428401470184326', '1.0888904333114624', '1.122296690940857', '0'],
       ['1.1134989261627197', '1.1219995021820068', '1.081270456314087', '1.0939244031906128',
        '0'],
       ['1.0969001054763794', '1.1705996990203857', '1.0850305557250977', '1.1340054273605347',
        '0'],
       ['1.1225990056991577', '1.1460003852844238', '1.1089695692062378', '1.1255937814712524

In [141]:
#usamos el valor close. Es el valor de cierre del tipo de cambio en un dia.Por lo que solo uso la columna 4
EUR_USD = np.genfromtxt('E:\FRANCO\Curso Data Analyst\S28 - A Loan Data Example with NumPy\EUR-USD.csv',
                        delimiter=',',
                        autostrip=True,
                        usecols=3,
                        skip_header=1)
EUR_USD

array([1.13, 1.12, 1.08, 1.11, 1.1 , 1.12, 1.09, 1.13, 1.13, 1.1 , 1.06, 1.09])

In [142]:
loan_data_strings[:,0]  #esta columna son los meses

array([ 5,  0,  9, ...,  6,  4, 12])

In [144]:
exchange_rate = loan_data_strings[:,0]
#asigno un tipo de valor de cambio a cada mes
for i in range(1,13):
    exchange_rate = np.where(exchange_rate==i,
                             EUR_USD[i-1],
                             exchange_rate)
#para las cuentas sin fecha de emision pongo el valor del promedio de cambio de ese año
exchange_rate = np.where(exchange_rate==0,
                             np.mean(EUR_USD),
                             exchange_rate)

exchange_rate

array([1.1 , 1.11, 1.13, ..., 1.12, 1.11, 1.09])

In [145]:
#para agregar este valor verifico si tienen las mismas formas
exchange_rate.shape

(10000,)

In [146]:
loan_data_numeric.shape

(10000, 6)

In [147]:
#como uno es 2D, debo redimensionar
exchange_rate = np.reshape(exchange_rate, (10000,1))

In [149]:
#agrego horizontalmente esta columna a los datos que tenia
loan_data_numeric = np.hstack((loan_data_numeric, exchange_rate))

In [152]:
#tengo que agregarlo tambien a las cabeceras
header_numeric = np.concatenate((header_numeric, np.array(['exchange_rate']))) #lo agrego como arreglo para que no de error
header_numeric

array(['id', 'loan_amnt', 'funded_amnt', 'int_rate', 'installment', 'total_pymnt', 'exchange_rate'],
      dtype='<U19')

    From US to EUR

In [153]:
header_numeric #vemos que 4 columnas tienen valores en dolares

array(['id', 'loan_amnt', 'funded_amnt', 'int_rate', 'installment', 'total_pymnt', 'exchange_rate'],
      dtype='<U19')

In [154]:
#creo un arreglo con las columnas que me interesan
columns_dollar = np.array([1,2,4,5])

In [156]:
loan_data_numeric[:,6]

array([1.1 , 1.11, 1.13, ..., 1.12, 1.11, 1.09])

In [158]:
#creo matrices apilando nuevas columnas, en las cuales divido el valor de las columnas de interes por el exchange_rate 
for i in columns_dollar:
    loan_data_numeric = np.hstack((loan_data_numeric, np.reshape(loan_data_numeric[:,i]/ loan_data_numeric[:,6],(10000,1))))

In [160]:
loan_data_numeric.shape #vemos que se agregaron las 4 columnas

(10000, 11)

In [161]:
loan_data_numeric

array([[48010226.  ,    35000.  ,    35000.  , ...,    31933.3 ,     1081.04,     8624.69],
       [57693261.  ,    30000.  ,    30000.  , ...,    27132.46,      848.86,     4232.39],
       [59432726.  ,    15000.  ,    15000.  , ...,    13326.3 ,      439.64,     1750.04],
       ...,
       [50415990.  ,    10000.  ,    10000.  , ...,     8910.3 ,     1223.36,     1947.47],
       [46154151.  ,    35000.  ,    10000.  , ...,     8997.4 ,      318.78,     2878.63],
       [66055249.  ,    10000.  ,    10000.  , ...,     9145.8 ,      283.49,      276.11]])

In [162]:
#Necesito expandir la cabecera (header) tambien

In [163]:
header_aditional = np.array([column_name + '_EUR' for column_name in header_numeric[columns_dollar]])

In [164]:
header_aditional

array(['loan_amnt_EUR', 'funded_amnt_EUR', 'installment_EUR', 'total_pymnt_EUR'], dtype='<U15')

In [165]:
#agrego este arreglo a la cabecera
header_numeric = np.concatenate((header_numeric, header_aditional))
header_numeric

array(['id', 'loan_amnt', 'funded_amnt', 'int_rate', 'installment', 'total_pymnt', 'exchange_rate',
       'loan_amnt_EUR', 'funded_amnt_EUR', 'installment_EUR', 'total_pymnt_EUR'], dtype='<U19')

In [166]:
#no esta claro que los otros valores esten en dolares por lo que lo modifico al nombre
header_numeric[columns_dollar] = np.array([column_name + '_USD' for column_name in header_numeric[columns_dollar]])

In [167]:
header_numeric

array(['id', 'loan_amnt_USD', 'funded_amnt_USD', 'int_rate', 'installment_USD', 'total_pymnt_USD',
       'exchange_rate', 'loan_amnt_EUR', 'funded_amnt_EUR', 'installment_EUR', 'total_pymnt_EUR'],
      dtype='<U19')

In [169]:
#quiero que las columnas de usd y eur esten una al lado de la otra, reordeno
columns_index_order = [0,1,7,2,8,3,4,9,5,10,6]

In [171]:
header_numeric = header_numeric[columns_index_order]

In [173]:
header_numeric #verifico

array(['id', 'loan_amnt_USD', 'loan_amnt_EUR', 'funded_amnt_USD', 'funded_amnt_EUR', 'int_rate',
       'installment_USD', 'installment_EUR', 'total_pymnt_USD', 'total_pymnt_EUR', 'exchange_rate'],
      dtype='<U19')

In [174]:
#lo mismo pero con las columnas 
loan_data_numeric = loan_data_numeric[:,columns_index_order]

In [175]:
loan_data_numeric

array([[48010226.  ,    35000.  ,    31933.3 , ...,     9452.96,     8624.69,        1.1 ],
       [57693261.  ,    30000.  ,    27132.46, ...,     4679.7 ,     4232.39,        1.11],
       [59432726.  ,    15000.  ,    13326.3 , ...,     1969.83,     1750.04,        1.13],
       ...,
       [50415990.  ,    10000.  ,     8910.3 , ...,     2185.64,     1947.47,        1.12],
       [46154151.  ,    35000.  ,    31490.9 , ...,     3199.4 ,     2878.63,        1.11],
       [66055249.  ,    10000.  ,     9145.8 , ...,      301.9 ,      276.11,        1.09]])

    Interest rate

In [176]:
header_numeric

array(['id', 'loan_amnt_USD', 'loan_amnt_EUR', 'funded_amnt_USD', 'funded_amnt_EUR', 'int_rate',
       'installment_USD', 'installment_EUR', 'total_pymnt_USD', 'total_pymnt_EUR', 'exchange_rate'],
      dtype='<U19')

In [177]:
loan_data_numeric[:,5]

array([13.33, 28.99, 28.99, ..., 28.99, 16.55, 28.99])

In [179]:
#divido por 100 para darle formato entre 0 y 1 en vez de porcentajes
loan_data_numeric[:,5] = loan_data_numeric[:,5]/100

In [180]:
loan_data_numeric[:,5]

array([0.13, 0.29, 0.29, ..., 0.29, 0.17, 0.29])

    CHECKPOINT 2: NUMERIC

In [182]:
checkpoint_numeric = checkpoint("Checkpoint-Numeric", header_numeric, loan_data_numeric)

In [183]:
checkpoint_numeric['header']

array(['id', 'loan_amnt_USD', 'loan_amnt_EUR', 'funded_amnt_USD', 'funded_amnt_EUR', 'int_rate',
       'installment_USD', 'installment_EUR', 'total_pymnt_USD', 'total_pymnt_EUR', 'exchange_rate'],
      dtype='<U19')

In [184]:
checkpoint_numeric['data']

array([[48010226.  ,    35000.  ,    31933.3 , ...,     9452.96,     8624.69,        1.1 ],
       [57693261.  ,    30000.  ,    27132.46, ...,     4679.7 ,     4232.39,        1.11],
       [59432726.  ,    15000.  ,    13326.3 , ...,     1969.83,     1750.04,        1.13],
       ...,
       [50415990.  ,    10000.  ,     8910.3 , ...,     2185.64,     1947.47,        1.12],
       [46154151.  ,    35000.  ,    31490.9 , ...,     3199.4 ,     2878.63,        1.11],
       [66055249.  ,    10000.  ,     9145.8 , ...,      301.9 ,      276.11,        1.09]])

    Creando el dataser Completo

In [185]:
#ahora voy a unir las partes numericas y strings en un solo dataset

In [186]:
checkpoint_numeric['data'].shape

(10000, 11)

In [187]:
checkpoint_strings['data'].shape

(10000, 6)

In [188]:
#como tienen el mismo numero de filas los puedo apilar uno al lado del otro

In [190]:
loan_data = np.hstack((checkpoint_numeric['data'], checkpoint_strings['data']))

In [191]:
loan_data

array([[48010226.  ,    35000.  ,    31933.3 , ...,       13.  ,        1.  ,        1.  ],
       [57693261.  ,    30000.  ,    27132.46, ...,        5.  ,        1.  ,        4.  ],
       [59432726.  ,    15000.  ,    13326.3 , ...,       10.  ,        1.  ,        4.  ],
       ...,
       [50415990.  ,    10000.  ,     8910.3 , ...,        5.  ,        1.  ,        1.  ],
       [46154151.  ,    35000.  ,    31490.9 , ...,       17.  ,        1.  ,        3.  ],
       [66055249.  ,    10000.  ,     9145.8 , ...,        4.  ,        0.  ,        3.  ]])

In [192]:
#verifico que no haya valores faltantes , ya que anteriormente los trate
np.isnan(loan_data).sum()

0

In [194]:
#concateno las cabeceras
header_full = np.concatenate((checkpoint_numeric['header'], checkpoint_strings['header']))

    Sorting (ordenando) el nuevo DataSet

In [198]:
#lo voy a ordenar de acuerdo a su id (columna 0)
loan_data = loan_data[np.argsort(loan_data[:,0])]

In [199]:
loan_data

array([[  373332.  ,     9950.  ,     9038.08, ...,       21.  ,        0.  ,        1.  ],
       [  575239.  ,    12000.  ,    10900.2 , ...,       25.  ,        1.  ,        2.  ],
       [  707689.  ,    10000.  ,     8924.3 , ...,       13.  ,        1.  ,        0.  ],
       ...,
       [68614880.  ,     5600.  ,     5121.65, ...,        8.  ,        1.  ,        1.  ],
       [68615915.  ,     4000.  ,     3658.32, ...,       10.  ,        1.  ,        2.  ],
       [68616519.  ,    21600.  ,    19754.93, ...,        3.  ,        0.  ,        2.  ]])

In [201]:
#verifico
np.argsort(loan_data[:,0])

array([   0,    1,    2, ..., 9997, 9998, 9999], dtype=int64)

In [203]:
#apilo la cabecera arriba de esta matriz
loan_data = np.vstack((header_full, loan_data))

In [204]:
#guardamos en un nuevo archivo
np.savetxt("loan-data.preprocessed.csv",
           loan_data,
           fmt='%s',
           delimiter=',')