In [1]:
import numpy as np

        Chequear si hay valores faltantes

In [2]:
lendig_co_numeric = np.loadtxt('E:\FRANCO\Curso Data Analyst\S27 - NumPy Preprocessing\Lending-company-Numeric.csv', delimiter =',')

In [3]:
#este metodo devuelve una matriz de boolean. True es si falta un valor y False que no.
#Sumando todo si el resultado es 0 significa que no hay valores faltantes

In [4]:
np.isnan(lendig_co_numeric).sum()

0

In [5]:
#usando loadtxt() cuando hay valores faltantes tira error, por eso uso genfromtxt()

In [6]:
lendig_co_numeric_NAN = np.genfromtxt('E:\FRANCO\Curso Data Analyst\S27 - NumPy Preprocessing\Lending-company-Numeric-NAN.csv', delimiter =';')

In [7]:
np.isnan(lendig_co_numeric_NAN) #veo que hay valores True, es decir que faltan

array([[False, False, False, False, False, False],
       [False, False, False, False, False, False],
       [False, False, False, False, False, False],
       ...,
       [ True, False, False, False, False, False],
       [False, False, False, False, False, False],
       [False, False, False, False, False, False]])

In [8]:
#uso el sum para ver cuantos faltan
np.isnan(lendig_co_numeric_NAN).sum()

260

In [9]:
#puedo pasar un parametro para rellenar los espacios vacios con un 0
lendig_co_numeric_NAN = np.genfromtxt('E:\FRANCO\Curso Data Analyst\S27 - NumPy Preprocessing\Lending-company-Numeric-NAN.csv',
                                      delimiter =';',
                                      filling_values =0)

In [10]:
np.isnan(lendig_co_numeric_NAN).sum() #ahora no tengo valores faltantes

0

In [11]:
#conviene reemplazar los valores faltantes No por 0 sino por algun numero que no represente nada en el dataset. Por ej un numero mayor que el
#num mas grande que tengo

In [12]:
lendig_co_numeric_NAN = np.genfromtxt('E:\FRANCO\Curso Data Analyst\S27 - NumPy Preprocessing\Lending-company-Numeric-NAN.csv',
                                      delimiter =';')

In [13]:
temporaly_fill = np.nanmax(lendig_co_numeric_NAN).round() +1

In [14]:
temporaly_fill

64002.0

In [15]:
#relleno los valores faltantes con la variable temporaly_fill
lendig_co_numeric_NAN = np.genfromtxt('E:\FRANCO\Curso Data Analyst\S27 - NumPy Preprocessing\Lending-company-Numeric-NAN.csv',
                                      delimiter =';',
                                      filling_values =temporaly_fill)

In [16]:
np.isnan(lendig_co_numeric_NAN).sum()

0

        Substituyendo valores faltantes

In [17]:
lendig_co_numeric_NAN = np.genfromtxt('E:\FRANCO\Curso Data Analyst\S27 - NumPy Preprocessing\Lending-company-Numeric-NAN.csv',
                                      delimiter =';')
lendig_co_numeric_NAN

array([[ 2000.,    40.,   365.,  3121.,  4241., 13621.],
       [ 2000.,    40.,   365.,  3061.,  4171., 15041.],
       [ 1000.,    40.,   365.,  2160.,  3280., 15340.],
       ...,
       [   nan,    40.,   365.,  4201.,  5001., 16600.],
       [ 1000.,    40.,   365.,  2080.,  3320., 15600.],
       [ 2000.,    40.,   365.,  4601.,  4601., 16600.]])

In [18]:
#una buena practica es reemplazar los valores por la media 
temporally_mean = np.nanmean(lendig_co_numeric_NAN, axis=0).round(2) #columnas

In [19]:
temporally_mean[0]

2250.25

In [20]:
temporaly_fill = np.nanmax(lendig_co_numeric_NAN).round(2) +1
lendig_co_numeric_NAN = np.genfromtxt('E:\FRANCO\Curso Data Analyst\S27 - NumPy Preprocessing\Lending-company-Numeric-NAN.csv',
                                      delimiter =';',
                                      filling_values =temporaly_fill)

In [21]:
temporaly_fill

64002.0

In [22]:
#vemos que ahora la media de la columna es el doble que la anterior, esto esta mal

In [23]:
np.mean(lendig_co_numeric_NAN[:,0]).round(2)

4263.25

In [24]:
#USO np.where() PARA RESOLVER ESTOS PROBLEMAS

In [25]:
lendig_co_numeric_NAN[:,0] = np.where(lendig_co_numeric_NAN[:,0] == temporaly_fill,
                                     temporally_mean[0],
                                      lendig_co_numeric_NAN[:,0])
#iguala los valores de relleno a la media de la columna,si no los deja como estan

In [26]:
#me fijo la media de la primer columna para verificar
np.mean(lendig_co_numeric_NAN[:,0]).round(2)

2250.25

In [27]:
#ahora hago lo mismo pero para todas las columnas
for i in range(lendig_co_numeric_NAN.shape[1]):
    lendig_co_numeric_NAN[:,i] = np.where(lendig_co_numeric_NAN[:,i] == temporaly_fill,
                                     temporally_mean[i],
                                      lendig_co_numeric_NAN[:,i])

In [28]:
#si quiero por ejemplo reemplazar todos los valores negativos a 0 
for i in range(lendig_co_numeric_NAN.shape[1]):
    lendig_co_numeric_NAN[:,i] = np.where(lendig_co_numeric_NAN[:,i] <0,
                                      0,
                                      lendig_co_numeric_NAN[:,i])

        Reshaping (cambiar la forma)

In [29]:
lending_co_numeric = np.loadtxt('E:\FRANCO\Curso Data Analyst\S27 - NumPy Preprocessing\Lending-company-Numeric.csv', delimiter =',')
lendig_co_numeric

array([[ 2000.,    40.,   365.,  3121.,  4241., 13621.],
       [ 2000.,    40.,   365.,  3061.,  4171., 15041.],
       [ 1000.,    40.,   365.,  2160.,  3280., 15340.],
       ...,
       [ 2000.,    40.,   365.,  4201.,  5001., 16600.],
       [ 1000.,    40.,   365.,  2080.,  3320., 15600.],
       [ 2000.,    40.,   365.,  4601.,  4601., 16600.]])

In [30]:
lendig_co_numeric.shape

(1043, 6)

In [31]:
np.reshape(lendig_co_numeric, (6,1043))

array([[ 2000.,    40.,   365., ...,   365.,  1581.,  3041.],
       [12277.,  2000.,    40., ...,    50.,   365.,  5350.],
       [ 6850., 15150.,  1000., ...,  2000.,    40.,   365.],
       [ 3101.,  4351., 16600., ..., 16600.,  2000.,    40.],
       [  365.,  3441.,  4661., ...,  8450., 22250.,  2000.],
       [   40.,   365.,  3701., ...,  4601.,  4601., 16600.]])

In [32]:
np.transpose(lendig_co_numeric)

array([[ 2000.,  2000.,  1000., ...,  2000.,  1000.,  2000.],
       [   40.,    40.,    40., ...,    40.,    40.,    40.],
       [  365.,   365.,   365., ...,   365.,   365.,   365.],
       [ 3121.,  3061.,  2160., ...,  4201.,  2080.,  4601.],
       [ 4241.,  4171.,  3280., ...,  5001.,  3320.,  4601.],
       [13621., 15041., 15340., ..., 16600., 15600., 16600.]])

In [33]:
#debe incluir exactamente la misma cantidad de elementos
np.reshape(lendig_co_numeric, (3,2086))

array([[ 2000.,    40.,   365., ...,    50.,   365.,  5350.],
       [ 6850., 15150.,  1000., ..., 16600.,  2000.,    40.],
       [  365.,  3441.,  4661., ...,  4601.,  4601., 16600.]])

In [34]:
#puedo cambiarla a 3 dimensiones o mas
np.reshape(lendig_co_numeric, (2,3,1043))

array([[[ 2000.,    40.,   365., ...,   365.,  1581.,  3041.],
        [12277.,  2000.,    40., ...,    50.,   365.,  5350.],
        [ 6850., 15150.,  1000., ...,  2000.,    40.,   365.]],

       [[ 3101.,  4351., 16600., ..., 16600.,  2000.,    40.],
        [  365.,  3441.,  4661., ...,  8450., 22250.,  2000.],
        [   40.,   365.,  3701., ...,  4601.,  4601., 16600.]]])

In [35]:
#No cambia las dimensiones de la matriz original por lo que tengo que guardar en una variable nueva
lendig_co_numeric

array([[ 2000.,    40.,   365.,  3121.,  4241., 13621.],
       [ 2000.,    40.,   365.,  3061.,  4171., 15041.],
       [ 1000.,    40.,   365.,  2160.,  3280., 15340.],
       ...,
       [ 2000.,    40.,   365.,  4201.,  5001., 16600.],
       [ 1000.,    40.,   365.,  2080.,  3320., 15600.],
       [ 2000.,    40.,   365.,  4601.,  4601., 16600.]])

In [36]:
lendig_co_numeric_2 = np.reshape(lendig_co_numeric, (6,1043))
lendig_co_numeric_2

array([[ 2000.,    40.,   365., ...,   365.,  1581.,  3041.],
       [12277.,  2000.,    40., ...,    50.,   365.,  5350.],
       [ 6850., 15150.,  1000., ...,  2000.,    40.,   365.],
       [ 3101.,  4351., 16600., ..., 16600.,  2000.,    40.],
       [  365.,  3441.,  4661., ...,  8450., 22250.,  2000.],
       [   40.,   365.,  3701., ...,  4601.,  4601., 16600.]])

In [37]:
#hay un metodo equivalente
lendig_co_numeric.reshape(6,1043)

array([[ 2000.,    40.,   365., ...,   365.,  1581.,  3041.],
       [12277.,  2000.,    40., ...,    50.,   365.,  5350.],
       [ 6850., 15150.,  1000., ...,  2000.,    40.,   365.],
       [ 3101.,  4351., 16600., ..., 16600.,  2000.,    40.],
       [  365.,  3441.,  4661., ...,  8450., 22250.,  2000.],
       [   40.,   365.,  3701., ...,  4601.,  4601., 16600.]])

        Removiendo valores

In [38]:
lendig_co_numeric

array([[ 2000.,    40.,   365.,  3121.,  4241., 13621.],
       [ 2000.,    40.,   365.,  3061.,  4171., 15041.],
       [ 1000.,    40.,   365.,  2160.,  3280., 15340.],
       ...,
       [ 2000.,    40.,   365.,  4201.,  5001., 16600.],
       [ 1000.,    40.,   365.,  2080.,  3320., 15600.],
       [ 2000.,    40.,   365.,  4601.,  4601., 16600.]])

In [39]:
np.delete(lendig_co_numeric, 0) #elimino el primer valor de la matriz

array([   40.,   365.,  3121., ...,  4601.,  4601., 16600.])

In [40]:
lendig_co_numeric.size

6258

In [41]:
#por mas que borre valores no se modifica la matriz original, tengo que guardar en una variable nueva
lendig_co_numeric

array([[ 2000.,    40.,   365.,  3121.,  4241., 13621.],
       [ 2000.,    40.,   365.,  3061.,  4171., 15041.],
       [ 1000.,    40.,   365.,  2160.,  3280., 15340.],
       ...,
       [ 2000.,    40.,   365.,  4201.,  5001., 16600.],
       [ 1000.,    40.,   365.,  2080.,  3320., 15600.],
       [ 2000.,    40.,   365.,  4601.,  4601., 16600.]])

In [42]:
#elimino la primera fila
np.delete(lendig_co_numeric, 0, axis=0)

array([[ 2000.,    40.,   365.,  3061.,  4171., 15041.],
       [ 1000.,    40.,   365.,  2160.,  3280., 15340.],
       [ 2000.,    40.,   365.,  3041.,  4241., 15321.],
       ...,
       [ 2000.,    40.,   365.,  4201.,  5001., 16600.],
       [ 1000.,    40.,   365.,  2080.,  3320., 15600.],
       [ 2000.,    40.,   365.,  4601.,  4601., 16600.]])

In [43]:
#elimino la primera columna
np.delete(lendig_co_numeric, 0, axis=1)

array([[   40.,   365.,  3121.,  4241., 13621.],
       [   40.,   365.,  3061.,  4171., 15041.],
       [   40.,   365.,  2160.,  3280., 15340.],
       ...,
       [   40.,   365.,  4201.,  5001., 16600.],
       [   40.,   365.,  2080.,  3320., 15600.],
       [   40.,   365.,  4601.,  4601., 16600.]])

In [44]:
#elimino la segunda columna
np.delete(lendig_co_numeric, 1, axis=1)

array([[ 2000.,   365.,  3121.,  4241., 13621.],
       [ 2000.,   365.,  3061.,  4171., 15041.],
       [ 1000.,   365.,  2160.,  3280., 15340.],
       ...,
       [ 2000.,   365.,  4201.,  5001., 16600.],
       [ 1000.,   365.,  2080.,  3320., 15600.],
       [ 2000.,   365.,  4601.,  4601., 16600.]])

In [45]:
#elimino la primera,tercera y quinta columna
np.delete(lendig_co_numeric, (0,2,4), axis=1)

array([[   40.,  3121., 13621.],
       [   40.,  3061., 15041.],
       [   40.,  2160., 15340.],
       ...,
       [   40.,  4201., 16600.],
       [   40.,  2080., 15600.],
       [   40.,  4601., 16600.]])

In [46]:
#elimino filas y columnas
np.delete(np.delete(lendig_co_numeric, (0,2,4), axis=1), (0,2,-1), axis=0)

array([[   40.,  3061., 15041.],
       [   40.,  3041., 15321.],
       [   50.,  3470., 13720.],
       ...,
       [   40.,  4240., 16600.],
       [   40.,  4201., 16600.],
       [   40.,  2080., 15600.]])

        Ordenando la data

In [47]:
lendig_co_numeric

array([[ 2000.,    40.,   365.,  3121.,  4241., 13621.],
       [ 2000.,    40.,   365.,  3061.,  4171., 15041.],
       [ 1000.,    40.,   365.,  2160.,  3280., 15340.],
       ...,
       [ 2000.,    40.,   365.,  4201.,  5001., 16600.],
       [ 1000.,    40.,   365.,  2080.,  3320., 15600.],
       [ 2000.,    40.,   365.,  4601.,  4601., 16600.]])

In [48]:
np.sort(lendig_co_numeric) #por defecto axis=-1 , que en este caso al ser 2D axis=1. Ordeno las filas en forma creciente

array([[   40.,   365.,  2000.,  3121.,  4241., 13621.],
       [   40.,   365.,  2000.,  3061.,  4171., 15041.],
       [   40.,   365.,  1000.,  2160.,  3280., 15340.],
       ...,
       [   40.,   365.,  2000.,  4201.,  5001., 16600.],
       [   40.,   365.,  1000.,  2080.,  3320., 15600.],
       [   40.,   365.,  2000.,  4601.,  4601., 16600.]])

In [49]:
np.sort(lendig_co_numeric, axis=0) #Ordeno las columnas en forma creciente

array([[ 1.0000e+03,  3.5000e+01,  3.6500e+02, -2.8700e+03, -2.8700e+03,
        -3.5000e+02],
       [ 1.0000e+03,  3.5000e+01,  3.6500e+02, -2.5500e+03, -2.1000e+03,
         1.5000e+02],
       [ 1.0000e+03,  3.5000e+01,  3.6500e+02, -2.4500e+03, -2.0000e+03,
         1.1000e+03],
       ...,
       [ 9.0000e+03,  1.2500e+02,  3.6500e+02,  1.6751e+04,  1.8751e+04,
         5.4625e+04],
       [ 9.0000e+03,  1.6500e+02,  3.6500e+02,  1.7650e+04,  2.0001e+04,
         5.4625e+04],
       [ 9.0000e+03,  1.6500e+02,  3.6500e+02,  1.9001e+04,  2.2001e+04,
         6.4001e+04]])

In [50]:
np.set_printoptions(suppress = True)#para hacer mas legible lo de arriba

In [51]:
np.sort(lendig_co_numeric, axis=None) #devuelve un 1D array ordenado

array([-2870., -2870., -2550., ..., 54625., 54625., 64001.])

In [52]:
#si quiero ordenar en forma descendente no hay parametro que lo haa automaticamente, pero puedo hacer:

In [53]:
np.sort(lendig_co_numeric)

array([[   40.,   365.,  2000.,  3121.,  4241., 13621.],
       [   40.,   365.,  2000.,  3061.,  4171., 15041.],
       [   40.,   365.,  1000.,  2160.,  3280., 15340.],
       ...,
       [   40.,   365.,  2000.,  4201.,  5001., 16600.],
       [   40.,   365.,  1000.,  2080.,  3320., 15600.],
       [   40.,   365.,  2000.,  4601.,  4601., 16600.]])

In [54]:
#multiplico por - adentro y afuera asi me queda ordenado al reves
-np.sort(-lendig_co_numeric)

array([[13621.,  4241.,  3121.,  2000.,   365.,    40.],
       [15041.,  4171.,  3061.,  2000.,   365.,    40.],
       [15340.,  3280.,  2160.,  1000.,   365.,    40.],
       ...,
       [16600.,  5001.,  4201.,  2000.,   365.,    40.],
       [15600.,  3320.,  2080.,  1000.,   365.,    40.],
       [16600.,  4601.,  4601.,  2000.,   365.,    40.]])

In [55]:
np.sort(lendig_co_numeric[:,3])#ordeno solo la cuarta columna

array([-2870., -2550., -2450., ..., 16751., 17650., 19001.])

In [56]:
#Para modificar la matriz original sin crear una nueva variable
lendig_co_numeric.sort(axis=0) #la sobreescribe
lendig_co_numeric

array([[ 1000.,    35.,   365., -2870., -2870.,  -350.],
       [ 1000.,    35.,   365., -2550., -2100.,   150.],
       [ 1000.,    35.,   365., -2450., -2000.,  1100.],
       ...,
       [ 9000.,   125.,   365., 16751., 18751., 54625.],
       [ 9000.,   165.,   365., 17650., 20001., 54625.],
       [ 9000.,   165.,   365., 19001., 22001., 64001.]])

            Argument Functions

In [57]:
lending_co_numeric = np.loadtxt('E:\FRANCO\Curso Data Analyst\S27 - NumPy Preprocessing\Lending-company-Numeric.csv', delimiter =',')
lendig_co_numeric

array([[ 1000.,    35.,   365., -2870., -2870.,  -350.],
       [ 1000.,    35.,   365., -2550., -2100.,   150.],
       [ 1000.,    35.,   365., -2450., -2000.,  1100.],
       ...,
       [ 9000.,   125.,   365., 16751., 18751., 54625.],
       [ 9000.,   165.,   365., 17650., 20001., 54625.],
       [ 9000.,   165.,   365., 19001., 22001., 64001.]])

In [58]:
    #np.argsort()

In [59]:
np.argsort(lendig_co_numeric)#muestra los indices de los numeros ordenados

array([[3, 4, 5, 1, 2, 0],
       [3, 4, 1, 5, 2, 0],
       [3, 4, 1, 2, 0, 5],
       ...,
       [1, 2, 0, 3, 4, 5],
       [1, 2, 0, 3, 4, 5],
       [1, 2, 0, 3, 4, 5]], dtype=int64)

In [60]:
np.argsort(lendig_co_numeric,axis=0) #ordena por columas pero tambien mostrando solo los indices

array([[   0,    0,    0,    0,    0,    0],
       [ 155,    1,  687,    1,    1,    1],
       [ 156,    2,  688,    2,    2,    2],
       ...,
       [1022, 1031,  355, 1040, 1040, 1040],
       [1031, 1041,  357, 1041, 1041, 1041],
       [1042, 1042, 1042, 1042, 1042, 1042]], dtype=int64)

In [61]:
lendig_co_numeric = lendig_co_numeric[np.argsort(lendig_co_numeric[:,0])] #ordeno la primer columna y dejo todo como estaba
lendig_co_numeric

array([[ 1000.,    35.,   365., -2870., -2870.,  -350.],
       [ 1000.,    40.,   365.,  2160.,  3350., 12431.],
       [ 1000.,    40.,   365.,  2160.,  3350., 12451.],
       ...,
       [ 9000.,   125.,   365., 12270., 15500., 24126.],
       [ 9000.,   125.,   365., 13001., 16576., 45745.],
       [ 9000.,   165.,   365., 19001., 22001., 64001.]])

In [62]:
lendig_co_numeric.argsort(axis=0) #este metodo no sobreescribe la matriz original

array([[   0,    0,    0,    0,    0,    0],
       [ 155,  157,  687,  155,  155,  155],
       [ 156,  156,  688,  156,  156,  156],
       ...,
       [1022, 1041,  355, 1023, 1023, 1023],
       [1031, 1031,  357, 1031, 1031, 1031],
       [1042, 1042, 1042, 1042, 1042, 1042]], dtype=int64)

In [63]:
lendig_co_numeric

array([[ 1000.,    35.,   365., -2870., -2870.,  -350.],
       [ 1000.,    40.,   365.,  2160.,  3350., 12431.],
       [ 1000.,    40.,   365.,  2160.,  3350., 12451.],
       ...,
       [ 9000.,   125.,   365., 12270., 15500., 24126.],
       [ 9000.,   125.,   365., 13001., 16576., 45745.],
       [ 9000.,   165.,   365., 19001., 22001., 64001.]])

In [64]:
    #np.argwhere()

In [65]:
lending_co_data_numeric = np.loadtxt('E:\FRANCO\Curso Data Analyst\S27 - NumPy Preprocessing\Lending-company-Numeric.csv', delimiter =',')
lending_co_data_numeric

array([[ 2000.,    40.,   365.,  3121.,  4241., 13621.],
       [ 2000.,    40.,   365.,  3061.,  4171., 15041.],
       [ 1000.,    40.,   365.,  2160.,  3280., 15340.],
       ...,
       [ 2000.,    40.,   365.,  4201.,  5001., 16600.],
       [ 1000.,    40.,   365.,  2080.,  3320., 15600.],
       [ 2000.,    40.,   365.,  4601.,  4601., 16600.]])

In [66]:
#muestra las coordenadas de los valores que cumplen una cierta condicion. Por defecto es !=0
np.argwhere(lending_co_data_numeric) #primera fila representa el indice de las filas y la 2da el indice de las columnas

array([[   0,    0],
       [   0,    1],
       [   0,    2],
       ...,
       [1042,    3],
       [1042,    4],
       [1042,    5]], dtype=int64)

In [67]:
#si quiero encontrar donde hay 0s
np.argwhere(lending_co_data_numeric == False)

array([[116,   4],
       [430,   3]], dtype=int64)

In [68]:
#puedo poner cualquier condicion
np.argwhere(lending_co_data_numeric%2 == 0)

array([[   0,    0],
       [   0,    1],
       [   1,    0],
       ...,
       [1042,    0],
       [1042,    1],
       [1042,    5]], dtype=int64)

In [69]:
lending_co_data_numeric_NAN = np.genfromtxt('E:\FRANCO\Curso Data Analyst\S27 - NumPy Preprocessing\Lending-company-Numeric-NAN.csv', delimiter =';')
lending_co_data_numeric_NAN

array([[ 2000.,    40.,   365.,  3121.,  4241., 13621.],
       [ 2000.,    40.,   365.,  3061.,  4171., 15041.],
       [ 1000.,    40.,   365.,  2160.,  3280., 15340.],
       ...,
       [   nan,    40.,   365.,  4201.,  5001., 16600.],
       [ 1000.,    40.,   365.,  2080.,  3320., 15600.],
       [ 2000.,    40.,   365.,  4601.,  4601., 16600.]])

In [70]:
#para dar las coordenadas de todos los elementos faltantes
np.argwhere(np.isnan(lending_co_data_numeric_NAN))

array([[  11,    3],
       [  15,    3],
       [  27,    3],
       [  58,    3],
       [  60,    4],
       [  85,    4],
       [ 117,    5],
       [ 152,    1],
       [ 152,    2],
       [ 152,    4],
       [ 172,    1],
       [ 175,    1],
       [ 175,    2],
       [ 176,    3],
       [ 177,    4],
       [ 178,    5],
       [ 211,    3],
       [ 229,    0],
       [ 230,    1],
       [ 237,    1],
       [ 247,    3],
       [ 251,    5],
       [ 252,    4],
       [ 258,    1],
       [ 260,    3],
       [ 262,    4],
       [ 271,    5],
       [ 272,    4],
       [ 284,    2],
       [ 284,    3],
       [ 297,    1],
       [ 297,    2],
       [ 300,    3],
       [ 315,    3],
       [ 315,    5],
       [ 327,    4],
       [ 336,    4],
       [ 343,    0],
       [ 344,    2],
       [ 346,    2],
       [ 363,    3],
       [ 375,    3],
       [ 377,    2],
       [ 398,    5],
       [ 416,    4],
       [ 428,    0],
       [ 432,    1],
       [ 433,

In [71]:
#verifico
lending_co_data_numeric_NAN[11]

array([ 2000.,    50.,   365.,    nan,  4190., 10790.])

In [72]:
#si quiero rellenar todos esos valores faltantes con 0s
for array_index in np.argwhere(np.isnan(lending_co_data_numeric_NAN)):
    lending_co_data_numeric_NAN[array_index[0],array_index[1]] = 0

In [73]:
lending_co_data_numeric_NAN[11]

array([ 2000.,    50.,   365.,     0.,  4190., 10790.])

        Shuffling Data

In [74]:
#voy a usar solo las 8 primeras filas para ver mejor
lending_co_data_numeric = np.loadtxt('E:\FRANCO\Curso Data Analyst\S27 - NumPy Preprocessing\Lending-company-Numeric.csv', delimiter =',')[:8]
lending_co_data_numeric

array([[ 2000.,    40.,   365.,  3121.,  4241., 13621.],
       [ 2000.,    40.,   365.,  3061.,  4171., 15041.],
       [ 1000.,    40.,   365.,  2160.,  3280., 15340.],
       [ 2000.,    40.,   365.,  3041.,  4241., 15321.],
       [ 2000.,    50.,   365.,  3470.,  4820., 13720.],
       [ 2000.,    40.,   365.,  3201.,  4141., 14141.],
       [ 2000.,    50.,   365.,  1851.,  3251., 17701.],
       [ 2000.,    40.,   365.,  3971.,  4131., 15351.]])

In [75]:
#Mezclo las filas para arriba o abajo
np.random.shuffle(lending_co_data_numeric)

In [76]:
lending_co_data_numeric

array([[ 2000.,    40.,   365.,  3061.,  4171., 15041.],
       [ 2000.,    50.,   365.,  1851.,  3251., 17701.],
       [ 2000.,    40.,   365.,  3041.,  4241., 15321.],
       [ 1000.,    40.,   365.,  2160.,  3280., 15340.],
       [ 2000.,    40.,   365.,  3121.,  4241., 13621.],
       [ 2000.,    40.,   365.,  3201.,  4141., 14141.],
       [ 2000.,    40.,   365.,  3971.,  4131., 15351.],
       [ 2000.,    50.,   365.,  3470.,  4820., 13720.]])

In [77]:
lending_co_data_numeric = np.loadtxt('E:\FRANCO\Curso Data Analyst\S27 - NumPy Preprocessing\Lending-company-Numeric.csv', delimiter =',')
lending_co_data_numeric

array([[ 2000.,    40.,   365.,  3121.,  4241., 13621.],
       [ 2000.,    40.,   365.,  3061.,  4171., 15041.],
       [ 1000.,    40.,   365.,  2160.,  3280., 15340.],
       ...,
       [ 2000.,    40.,   365.,  4201.,  5001., 16600.],
       [ 1000.,    40.,   365.,  2080.,  3320., 15600.],
       [ 2000.,    40.,   365.,  4601.,  4601., 16600.]])

In [78]:
from numpy.random import shuffle

In [79]:
#ahora directamente lo llamo asi
shuffle(lending_co_data_numeric)
lending_co_data_numeric

array([[ 1000.,    50.,   365.,   900.,  2150., 19250.],
       [ 4000.,    50.,   365.,  7000., 10000., 22250.],
       [ 2000.,    40.,   365.,  3401.,  4781., 16421.],
       ...,
       [ 2000.,    40.,   365.,  3321.,  4221., 12541.],
       [ 2000.,    40.,   365.,  3221.,  4421., 16541.],
       [ 1000.,    50.,   365., -2400., -1750.,  1830.]])

In [80]:
#otra forma de barajar (shuffle)

In [81]:
from numpy.random import Generator as gen
from numpy.random import PCG64 as pcg

In [82]:
array_RG = gen(pcg())
array_RG.shuffle(lending_co_data_numeric)
lending_co_data_numeric

array([[ 2000.,    50.,   365.,  4401.,  5301., 20250.],
       [ 2000.,    40.,   365.,  3401.,  4601., 16600.],
       [ 2000.,    40.,   365.,  4701.,  6201., 14401.],
       ...,
       [ 4000.,    50.,   365.,  5250.,  6750.,  8250.],
       [ 2000.,    50.,   365.,  3501.,  5131., 18081.],
       [ 1000.,    50.,   365., -2000.,  -550., 13850.]])

        CASTING

In [83]:
lending_co_data_numeric = np.loadtxt('E:\FRANCO\Curso Data Analyst\S27 - NumPy Preprocessing\Lending-company-Numeric.csv', delimiter =',')
lending_co_data_numeric

array([[ 2000.,    40.,   365.,  3121.,  4241., 13621.],
       [ 2000.,    40.,   365.,  3061.,  4171., 15041.],
       [ 1000.,    40.,   365.,  2160.,  3280., 15340.],
       ...,
       [ 2000.,    40.,   365.,  4201.,  5001., 16600.],
       [ 1000.,    40.,   365.,  2080.,  3320., 15600.],
       [ 2000.,    40.,   365.,  4601.,  4601., 16600.]])

In [84]:
#cambio el tipo de datos a enteros
lending_co_data_numeric.astype(dtype = np.int32)

array([[ 2000,    40,   365,  3121,  4241, 13621],
       [ 2000,    40,   365,  3061,  4171, 15041],
       [ 1000,    40,   365,  2160,  3280, 15340],
       ...,
       [ 2000,    40,   365,  4201,  5001, 16600],
       [ 1000,    40,   365,  2080,  3320, 15600],
       [ 2000,    40,   365,  4601,  4601, 16600]])

In [85]:
#cambio el tipo de datos a string
lending_co_data_numeric.astype(dtype = str)

array([['2000.0', '40.0', '365.0', '3121.0', '4241.0', '13621.0'],
       ['2000.0', '40.0', '365.0', '3061.0', '4171.0', '15041.0'],
       ['1000.0', '40.0', '365.0', '2160.0', '3280.0', '15340.0'],
       ...,
       ['2000.0', '40.0', '365.0', '4201.0', '5001.0', '16600.0'],
       ['1000.0', '40.0', '365.0', '2080.0', '3320.0', '15600.0'],
       ['2000.0', '40.0', '365.0', '4601.0', '4601.0', '16600.0']],
      dtype='<U32')

        Stripping values (eliminar valores)

In [86]:
lending_co_total_price = np.genfromtxt('E:\FRANCO\Curso Data Analyst\S27 - NumPy Preprocessing\Lending-Company-Total-Price.csv',
                                      delimiter=',',
                                      dtype = str,
                                      skip_header=1,
                                      usecols=[1,2,4])
lending_co_total_price

array([['id_1', 'Product B', 'Location 2'],
       ['id_2', 'Product B', 'Location 3'],
       ['id_3', 'Product C', 'Location 5'],
       ...,
       ['id_413', 'Product B', 'Location 135'],
       ['id_414', 'Product C', 'Location 200'],
       ['id_415', 'Product A', 'Location 8']], dtype='<U12')

In [87]:
#vou a quitar parte de los string, no todo el valor. 

In [90]:
#elimino el id_, Product y Location
lending_co_total_price[:,0] = np.chararray.strip(lending_co_total_price[:,0],"id_")
lending_co_total_price[:,1] = np.chararray.strip(lending_co_total_price[:,1],"Product ")
lending_co_total_price[:,2] = np.chararray.strip(lending_co_total_price[:,2],"Location ")
lending_co_total_price

array([['1', 'B', '2'],
       ['2', 'B', '3'],
       ['3', 'C', '5'],
       ...,
       ['413', 'B', '135'],
       ['414', 'C', '200'],
       ['415', 'A', '8']], dtype='<U12')

In [92]:
#si quiero transformar las letras A,B,C, en valores numericos
lending_co_total_price[:,1] = np.where(lending_co_total_price[:,1] == 'A', 1, lending_co_total_price[:,1])
lending_co_total_price[:,1] = np.where(lending_co_total_price[:,1] == 'B', 2, lending_co_total_price[:,1])
lending_co_total_price[:,1] = np.where(lending_co_total_price[:,1] == 'C', 3, lending_co_total_price[:,1])
lending_co_total_price[:,1] = np.where(lending_co_total_price[:,1] == 'D', 4, lending_co_total_price[:,1])
lending_co_total_price[:,1] = np.where(lending_co_total_price[:,1] == 'E', 5, lending_co_total_price[:,1])
lending_co_total_price[:,1] = np.where(lending_co_total_price[:,1] == 'F', 6, lending_co_total_price[:,1])

lending_co_total_price

array([['1', '2', '2'],
       ['2', '2', '3'],
       ['3', '3', '5'],
       ...,
       ['413', '2', '135'],
       ['414', '3', '200'],
       ['415', '1', '8']], dtype='<U12')

In [93]:
#los paso a enteros
lending_co_total_price = lending_co_total_price.astype(dtype = np.int32)
lending_co_total_price

array([[  1,   2,   2],
       [  2,   2,   3],
       [  3,   3,   5],
       ...,
       [413,   2, 135],
       [414,   3, 200],
       [415,   1,   8]])

        Stacking (apilamiento)

In [94]:
lending_co_data_numeric = np.loadtxt('E:\FRANCO\Curso Data Analyst\S27 - NumPy Preprocessing\Lending-company-Numeric.csv', delimiter =',')
lending_co_data_numeric

array([[ 2000.,    40.,   365.,  3121.,  4241., 13621.],
       [ 2000.,    40.,   365.,  3061.,  4171., 15041.],
       [ 1000.,    40.,   365.,  2160.,  3280., 15340.],
       ...,
       [ 2000.,    40.,   365.,  4201.,  5001., 16600.],
       [ 1000.,    40.,   365.,  2080.,  3320., 15600.],
       [ 2000.,    40.,   365.,  4601.,  4601., 16600.]])

In [97]:
lending_co_data_numeric_NAN = np.genfromtxt('E:\FRANCO\Curso Data Analyst\S27 - NumPy Preprocessing\Lending-company-Numeric-NAN.csv', delimiter =';')
#reemplazo los valores faltantes por la media de cada columa
temporary_fill = np.nanmax(lending_co_data_numeric_NAN).round(2) +1
temporary_mean = np.nanmean(lending_co_data_numeric_NAN, axis=0).round(2)

lending_co_data_numeric_NAN = np.genfromtxt('E:\FRANCO\Curso Data Analyst\S27 - NumPy Preprocessing\Lending-company-Numeric-NAN.csv',
                                            delimiter =';',
                                           filling_values = temporary_fill)

for i in range(lending_co_data_numeric_NAN.shape[1]):
    lending_co_data_numeric_NAN[:,i] = np.where(lending_co_data_numeric_NAN[:,i]==temporary_fill,
                                               temporary_mean[i],
                                               lending_co_data_numeric_NAN[:,i])

lending_co_data_numeric_NAN

array([[ 2000.  ,    40.  ,   365.  ,  3121.  ,  4241.  , 13621.  ],
       [ 2000.  ,    40.  ,   365.  ,  3061.  ,  4171.  , 15041.  ],
       [ 1000.  ,    40.  ,   365.  ,  2160.  ,  3280.  , 15340.  ],
       ...,
       [ 2250.25,    40.  ,   365.  ,  4201.  ,  5001.  , 16600.  ],
       [ 1000.  ,    40.  ,   365.  ,  2080.  ,  3320.  , 15600.  ],
       [ 2000.  ,    40.  ,   365.  ,  4601.  ,  4601.  , 16600.  ]])

In [98]:
#stackin es poner multiples objetos uno encima del otro para crear un objeto mas grande

In [100]:
np.stack((lending_co_data_numeric[:,0], lending_co_data_numeric[:,1])) #tome las 2 primeras columnas y las apile como si fueran 2 filas 

array([[2000., 2000., 1000., ..., 2000., 1000., 2000.],
       [  40.,   40.,   40., ...,   40.,   40.,   40.]])

In [102]:
#si las quiero apilar como columnas una al lado de la otra
np.stack((lending_co_data_numeric[:,0], lending_co_data_numeric[:,1],lending_co_data_numeric[:,2]),axis=1)

array([[2000.,   40.,  365.],
       [2000.,   40.,  365.],
       [1000.,   40.,  365.],
       ...,
       [2000.,   40.,  365.],
       [1000.,   40.,  365.],
       [2000.,   40.,  365.]])

In [106]:
#apilando 2 matrices verticalmente
np.vstack((lending_co_data_numeric, lending_co_data_numeric_NAN)).shape #shape para ver la forma y comprobar que se apilaron

(2086, 6)

In [107]:
#apilando 2 matrices horizontalmente
np.hstack((lending_co_data_numeric, lending_co_data_numeric_NAN)).shape

(1043, 12)

In [109]:
#añade una dimension a la matriz, como si la hiciera 3D
np.dstack((lending_co_data_numeric, lending_co_data_numeric_NAN)).shape

(1043, 6, 2)

In [111]:
#puedo obtener el mismo resultado que dtack para matrices 2D. Para mas dimensiones NO sirve
np.stack((lending_co_data_numeric, lending_co_data_numeric_NAN), axis=-1)

array([[[ 2000.  ,  2000.  ],
        [   40.  ,    40.  ],
        [  365.  ,   365.  ],
        [ 3121.  ,  3121.  ],
        [ 4241.  ,  4241.  ],
        [13621.  , 13621.  ]],

       [[ 2000.  ,  2000.  ],
        [   40.  ,    40.  ],
        [  365.  ,   365.  ],
        [ 3061.  ,  3061.  ],
        [ 4171.  ,  4171.  ],
        [15041.  , 15041.  ]],

       [[ 1000.  ,  1000.  ],
        [   40.  ,    40.  ],
        [  365.  ,   365.  ],
        [ 2160.  ,  2160.  ],
        [ 3280.  ,  3280.  ],
        [15340.  , 15340.  ]],

       ...,

       [[ 2000.  ,  2250.25],
        [   40.  ,    40.  ],
        [  365.  ,   365.  ],
        [ 4201.  ,  4201.  ],
        [ 5001.  ,  5001.  ],
        [16600.  , 16600.  ]],

       [[ 1000.  ,  1000.  ],
        [   40.  ,    40.  ],
        [  365.  ,   365.  ],
        [ 2080.  ,  2080.  ],
        [ 3320.  ,  3320.  ],
        [15600.  , 15600.  ]],

       [[ 2000.  ,  2000.  ],
        [   40.  ,    40.  ],
        [  365.  

        Concatenate

In [112]:
lending_co_data_numeric = np.loadtxt('E:\FRANCO\Curso Data Analyst\S27 - NumPy Preprocessing\Lending-company-Numeric.csv', delimiter =',')
lending_co_data_numeric

array([[ 2000.,    40.,   365.,  3121.,  4241., 13621.],
       [ 2000.,    40.,   365.,  3061.,  4171., 15041.],
       [ 1000.,    40.,   365.,  2160.,  3280., 15340.],
       ...,
       [ 2000.,    40.,   365.,  4201.,  5001., 16600.],
       [ 1000.,    40.,   365.,  2080.,  3320., 15600.],
       [ 2000.,    40.,   365.,  4601.,  4601., 16600.]])

In [113]:
#concateno las 2  primeras filas para obtener una fila mas larga
np.concatenate((lending_co_data_numeric[0,:], lending_co_data_numeric[1,:]))

array([ 2000.,    40.,   365.,  3121.,  4241., 13621.,  2000.,    40.,
         365.,  3061.,  4171., 15041.])

In [116]:
#concatenando las 2 matrices. Es simililar al vstack()
np.concatenate((lending_co_data_numeric,lending_co_data_numeric_NAN))

array([[ 2000.  ,    40.  ,   365.  ,  3121.  ,  4241.  , 13621.  ],
       [ 2000.  ,    40.  ,   365.  ,  3061.  ,  4171.  , 15041.  ],
       [ 1000.  ,    40.  ,   365.  ,  2160.  ,  3280.  , 15340.  ],
       ...,
       [ 2250.25,    40.  ,   365.  ,  4201.  ,  5001.  , 16600.  ],
       [ 1000.  ,    40.  ,   365.  ,  2080.  ,  3320.  , 15600.  ],
       [ 2000.  ,    40.  ,   365.  ,  4601.  ,  4601.  , 16600.  ]])

In [115]:
np.concatenate((lending_co_data_numeric,lending_co_data_numeric_NAN)).shape

(2086, 6)

In [117]:
#concatenando las 2 matrices. Es simililar al hstack()
np.concatenate((lending_co_data_numeric,lending_co_data_numeric_NAN), axis=1)

array([[ 2000.,    40.,   365., ...,  3121.,  4241., 13621.],
       [ 2000.,    40.,   365., ...,  3061.,  4171., 15041.],
       [ 1000.,    40.,   365., ...,  2160.,  3280., 15340.],
       ...,
       [ 2000.,    40.,   365., ...,  4201.,  5001., 16600.],
       [ 1000.,    40.,   365., ...,  2080.,  3320., 15600.],
       [ 2000.,    40.,   365., ...,  4601.,  4601., 16600.]])

In [118]:
np.concatenate((lending_co_data_numeric,lending_co_data_numeric_NAN), axis=1).shape

(1043, 12)

In [120]:
#concateno dos 1D que tienen diferentes dimensiones. Una columna y una fila
np.concatenate((lending_co_data_numeric[0,:], lending_co_data_numeric[:,0])) #No hay ningun problema

array([2000.,   40.,  365., ..., 2000., 1000., 2000.])

        UNIQUE

In [126]:
#crea una matriz con todos los valores diferentes y los ordena en valor ascendente. Si son letras ordena de acuerdo a ASCII
np.unique(lending_co_data_numeric[:,1], return_counts=True, return_index=True) 
                    #valores de la segunda columna ,index en donde esta el primer valor, cantidad que se repite cada valor

(array([ 35.,  40.,  50., 125., 165.]),
 array([327,   0,   4,  19,  27], dtype=int64),
 array([  4, 567, 451,  19,   2], dtype=int64))