In [1]:
import numpy as np

In [2]:
#mean() function

In [3]:
matrix_A = np.array([[1,0,0,3,1],[3,6,6,2,9],[4,5,3,8,0]])
matrix_A

array([[1, 0, 0, 3, 1],
       [3, 6, 6, 2, 9],
       [4, 5, 3, 8, 0]])

        Promedio

In [5]:
#promedio de todos los elementos
np.mean(matrix_A)

3.4

In [6]:
#promedio primera fila
np.mean(matrix_A[0])

1.0

In [8]:
#promedio primer columna
np.mean(matrix_A[:,0])

2.6666666666666665

In [9]:
#promedio de todas las columnas
np.mean(matrix_A, axis=0)

array([2.66666667, 3.66666667, 3.        , 4.33333333, 3.33333333])

In [10]:
#promedio de todas las filas
np.mean(matrix_A, axis=1)

array([1. , 5.2, 4. ])

        Valores maximos y minimos

In [11]:
#valor mas chico de la matriz
np.min(matrix_A)

0

In [12]:
#valor mas chico de la fila 2
np.min(matrix_A[1])

2

In [13]:
#valor minimo de un array. Funciona igual que min()
np.amin(matrix_A[1])

2

In [14]:
#toma dos matrices o arreglos y crea una nueva con los valores mimnimos comparando las 2
np.minimum(matrix_A[0], matrix_A[2])

array([1, 0, 0, 3, 0])

In [15]:
#puedo dividir la matriz por filas con reduce
np.minimum.reduce(matrix_A)

array([1, 0, 0, 2, 0])

In [16]:
np.max(matrix_A)

9

In [17]:
np.amax(matrix_A)

9

In [18]:
np.maximum.reduce(matrix_A)

array([4, 6, 6, 8, 9])

        Statistical order functions

In [19]:
matrix_A

array([[1, 0, 0, 3, 1],
       [3, 6, 6, 2, 9],
       [4, 5, 3, 8, 0]])

In [20]:
#peack to peack. Devuelve la diferencia entre el valor mas alto y el mas bajo
np.ptp(matrix_A)

9

In [21]:
np.ptp(matrix_A, axis=0)

array([3, 6, 6, 6, 9])

In [22]:
np.ptp(matrix_A, axis=1)

array([3, 7, 8])

In [23]:
#percentile 70 es mayor al 70% de los valores

In [25]:
np.sort(matrix_A, axis=None) #ordeno la matriz para visualizar mejor

array([0, 0, 0, 1, 1, 2, 3, 3, 3, 4, 5, 6, 6, 8, 9])

In [29]:
#toma el valor en el 70% de la matriz, como tengo 15 datos seria entre el dato 10 y 11 (4 y 5 en este caso).Usa interpolacion
np.percentile(matrix_A, 70, interpolation ="midpoint")

4.5

In [33]:
#con percentile = 50 tengo la mediana. Con 0 tengo el minimo y con 100 el maximo
np.percentile(matrix_A, 50)

3.0

In [35]:
#quantile es como el percentile pero va de 0 a 1
np.quantile(matrix_A, 0.70, interpolation= "midpoint")

4.5

        Average and variances

In [37]:
#mediana: valor medio de la matriz ordenada
np.median(matrix_A)

3.0

In [38]:
np.mean(matrix_A)

3.4

In [40]:
#promedio. Igual que la media
np.average(matrix_A)

3.4

In [43]:
#veo la diferencia entre media y promedio. Genero valores aleatorios primero
from numpy.random import Generator as gen
from numpy.random import PCG64 as pcg

array_RG = gen(pcg(365))

array_weights = array_RG.random(size=(3,5))
array_weights

array([[0.75915734, 0.7662218 , 0.6291028 , 0.20336599, 0.66501486],
       [0.06559111, 0.71326309, 0.10812106, 0.87969046, 0.49405844],
       [0.82472673, 0.45652944, 0.07367232, 0.69628564, 0.36690736]])

In [45]:
np.average(array_weights, weights = array_weights)

0.662051781817159

In [47]:
np.mean(array_weights)

0.5134472293714308

In [49]:
#varianza 
np.var(matrix_A)

7.84

In [50]:
#standar desviation
np.std(matrix_A)

2.8

In [51]:
#verificando que el cuadrado de la desviacion estandar es la varianza
2.8**2

7.839999999999999

        Covarianza y correlacion

In [52]:
#covarianza
np.cov(matrix_A)

array([[ 1.5, -2. ,  2. ],
       [-2. ,  7.7, -7. ],
       [ 2. , -7. ,  8.5]])

In [53]:
#correlacion es la covarianza/producto de las desviaciones tipicas. 
np.corrcoef(matrix_A)

array([[ 1.        , -0.58848989,  0.56011203],
       [-0.58848989,  1.        , -0.8652532 ],
       [ 0.56011203, -0.8652532 ,  1.        ]])